services:
  minio:
    image: minio/minio:latest
    container_name: machineguard-minio
    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-machineguard}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-machineguard123}

    volumes:
      - minio_data:/data

    ports:
      - "9000:9000"
      - "9001:9001"

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

    restart: unless-stopped

  minio-init:
    image: minio/mc:latest
    container_name: machineguard-minio-init

    depends_on:
      minio:
        condition: service_healthy

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-machineguard}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-machineguard123}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:-machineguard-mlops-artifacts}

    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e

        mc alias set local \
          http://minio:9000 \
          "$${MINIO_ROOT_USER}" \
          "$${MINIO_ROOT_PASSWORD}"

        mc mb --ignore-existing \
          "local/$${S3_BUCKET_NAME}"

        mc anonymous set private \
          "local/$${S3_BUCKET_NAME}"

        echo "MinIO bucket initialized successfully."

    restart: "no"

volumes:
  minio_data:
    name: machineguard_minio_data