services:
  - type: web
    name: machineguard-api

    runtime: docker

    dockerfilePath: ./Dockerfile

    plan: free

    autoDeploy: true

    healthCheckPath: /health

    envVars:

      - key: LOG_LEVEL
        value: INFO

      - key: MODEL_NAME
        value: MachineGuardFailureClassifier

      - key: MODEL_ALIAS
        value: champion